In [3]:
import pandas as pd
import requests
import numpy as np

In [2]:
file_name="df_garages_2022-12-22.gzip"

In [4]:
file_name_desc=(file_name[:-5]+"_desc.gzip")
df=pd.read_parquet(file_name)
df_desc=pd.read_parquet(file_name_desc)

In [5]:
df.head()

,hash_id,price,price_czk,area,lat,lon,locality,type,category,is_auction,exclusively_at_rk,category_main_cb,category_sub_cb,category_type_cb,company_id,company_name
0,2670483276,1225000.0,1225000.0,21.0,50.035338,14.458362,Praha 4 - Michle,1,5,False,0,5,52,1,43314.0,Duna House
1,2495821644,1758000.0,1758000.0,21.0,50.057895,14.518219,Praha 10 - Strašnice,1,5,False,1,5,34,1,NaN,None
2,156955724,2000.0,2000.0,13.0,50.064158,14.500559,Praha 10 - Strašnice,2,5,False,1,5,34,2,NaN,None
3,2362082380,558000.0,558000.0,17.0,49.997397,14.413837,Praha 4 - Modřany,1,5,False,0,5,34,1,NaN,None
4,377640780,395000.0,395000.0,16.0,50.100554,14.498755,Praha 9 - Prosek,1,5,False,1,5,52,1,14367.0,Home Real Estate

In [6]:
df_desc.head()

,description,discounted,price_original,id_order,date_update,building_type,building_condition,building_location,area_net,area_floor,...,heating,telecommunication,date_year_reconstruction,energy_efficient_rating_card,availability,date_offer_start,energy_efficient_rating_index,date_tour,date_tour_to,area_garden
2670483276,Prodávám garážové stání v osobním vlastnictví ...,None,None,GR145386,Včera,Cihlová,Velmi dobrý,Klidná část obce,19,19,...,None,None,NaN,None,None,None,None,None,None,None
2495821644,Nabízím k prodeji zděnou garáž o velikosti 16 ...,None,None,14425911,Včera,Cihlová,Dobrý,None,19,None,...,None,None,NaN,None,None,None,None,None,None,None
156955724,Nabízíme garážové stání k pronájmu ve druhém p...,None,None,0384,Včera,Cihlová,Velmi dobrý,Centrum obce,12,None,...,None,None,NaN,None,None,None,None,None,None,None
2362082380,Nabízíme k prodeji parkovací stání o rozměrech...,None,None,PS.22,Včera,Smíšená,Novostavba,Klidná část obce,15,None,...,None,None,NaN,None,None,None,None,None,None,None
377640780,Společnost Home Real Estate nabízí na prodej v...,None,None,36008,Včera,Cihlová,Velmi dobrý,None,14,None,...,None,None,NaN,None,None,None,None,None,None,None