In [1]:
!pip install --upgrade redataprocessing

Requirement already satisfied: redataprocessing in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (0.0.17)
Collecting redataprocessing
  Downloading redataprocessing-0.0.18-py3-none-any.whl (14 kB)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from redataprocessing) (1.5.3)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from redataprocessing) (1.24.1)
Requirement already satisfied: certifi in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from redataprocessing) (2022.12.7)
Requirement already satisfied: aiohttp in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from redataprocessing) (3.8.3)
Requirement already satisfied: nest-asyncio in /Users/vojtechkania/Library/Python/3.11/lib/python/site-packages (from redataprocessing) (1.5.6)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from redataprocessing) (2.28.2)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from redataprocessing) (4.64.1)
Requirement already satisfied: typing in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from redataprocessing) (3.7.4.3)
Requirement already satisfied: asyncio in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from redataprocessing) (3.4.3)
Requirement already satisfied: attrs>=17.3.0 in /Users/vojtechkania/Library/Python/3.11/lib/python/site-packages (from aiohttp->redataprocessing) (22.2.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->redataprocessing) (2.1.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->redataprocessing) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->redataprocessing) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->redataprocessing) (1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->redataprocessing) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiohttp->redataprocessing) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/vojtechkania/Library/Python/3.11/lib/python/site-packages (from pandas->redataprocessing) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas->redataprocessing) (2022.7.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/vojtechkania/Library/Python/3.11/lib/python/site-packages (from requests->redataprocessing) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->redataprocessing) (1.26.14)
Requirement already satisfied: six>=1.5 in /Users/vojtechkania/Library/Python/3.11/lib/python/site-packages (from python-dateutil>=2.8.1->pandas->redataprocessing) (1.16.0)
Installing collected packages: redataprocessing
  Attempting uninstall: redataprocessing
    Found existing installation: redataprocessing 0.0.17
    Uninstalling redataprocessing-0.0.17:
      Successfully uninstalled redataprocessing-0.0.17
Successfully installed redataprocessing-0.0.18

In [2]:
import redataprocessing as rdp
dir(rdp)

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/redataprocessing/sreality.py:30: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

['Dict',
 'Optional',
 'Tuple',
 'Union',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'aiohttp',
 'asyncio',
 'category_main_dict',
 'category_sub_dict',
 'category_type_dict',
 'certifi',
 'columns_w_list',
 'create_db_table_name',
 'date',
 'db_table_names_main',
 'db_table_names_type',
 'decode_collector',
 'description_decoding',
 'description_items_dict',
 'download_lists',
 'download_re_offers',
 'get_area_from_name',
 'get_company_details',
 'get_flat_type_from_name',
 'get_gps_lat_lon',
 'get_re_offers',
 'get_re_offers_description',
 'get_response',
 'get_responses',
 'get_swap_dict',
 'getting_offers_without_downloaded_description',
 'individual_description_into_pd_df',
 'locality_region_id_dict',
 'main',
 'nest_asyncio',
 'note_missing_values',
 'np',
 'os',
 'pd',
 'randint',
 're',
 'requests',
 'save_re_offers',
 'save_to_db',
 'sleep',
 'sqlite3',
 'sreality',
 'sreality_api_dictionaries',
 'sreality_description_asyncio',
 'sreality_description_download_decoding',
 'ssl',
 'sys',
 'tqdm',
 'transformer',
 'urls_from_indices']

In [3]:
import pkgutil

package = rdp
prefix = package.__name__ + "."
for importer, modname, ispkg in pkgutil.iter_modules(package.__path__, prefix):
    print("Found submodule %s (is a package: %s)" % (modname, ispkg))
    module = __import__(modname, fromlist="dummy")
    print("Imported", module)

Found submodule redataprocessing.sreality (is a package: False)
Imported <module 'redataprocessing.sreality' from '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/redataprocessing/sreality.py'>
Found submodule redataprocessing.sreality_api_dictionaries (is a package: False)
Imported <module 'redataprocessing.sreality_api_dictionaries' from '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/redataprocessing/sreality_api_dictionaries.py'>
Found submodule redataprocessing.sreality_description_asyncio (is a package: False)
Imported <module 'redataprocessing.sreality_description_asyncio' from '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/redataprocessing/sreality_description_asyncio.py'>
Found submodule redataprocessing.sreality_description_download_decoding (is a package: False)
Imported <module 'redataprocessing.sreality_description_download_decoding' from '/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/redataprocessing/sreality_description_download_decoding.py'>

**We use function get_re_offers to request the data for specified categories:**

If one plug in invalid arguments, they will be notified. For example:

In [4]:
rdp.get_re_offers(path_to_sqlite="estate_data.sqlite", 
category_main="apartments", 
category_type="sale", 
locality_region=["Germany"])

ValueError: locality_region: must be one of ['Jihočeský kraj', 'Plzeňský kraj', 'Karlovarský kraj', 'Ústecký kraj', 'Liberecký kraj', 'Královéhradecký kraj', 'Pardubický kraj', 'Olomoucký kraj', 'Zlínský kraj', 'Hlavní město Praha', 'Středočeský kraj', 'Moravskoslezský kraj', 'Kraj Vysočina', 'Jihomoravský kraj'].

In [5]:
rdp.get_re_offers(path_to_sqlite="estate_data.sqlite", 
category_main="apartments", 
category_type="sale", 
locality_region=["Královéhradecký kraj"])

resulting data will be saved to current working directory (/Users/vojtechkania/Desktop/re_data_processing)
initiating download of offers
starting sleep
downloaded list of offers: page 1
starting sleep
downloaded list of offers: page 2
starting sleep
downloaded list of offers: page 3
starting sleep
downloaded list of offers: page 4
starting sleep
downloaded list of offers: page 5
starting sleep
downloaded list of offers: page 6
starting sleep
downloaded list of offers: page 7
starting sleep
downloaded list of offers: page 8
starting sleep
downloaded list of offers: page 9
starting sleep
downloaded list of offers: page 10
starting sleep
downloaded list of offers: page 11
starting sleep
downloaded list of offers: page 12
starting sleep
downloaded list of offers: page 13
starting sleep
downloaded list of offers: page 14
starting sleep
downloading of offers finished

decoding pages with offers:   0%|          | 0/14 [00:00<?, ?it/s]

saving offers to database (table name OFFERS_APARTMENTS_SALE)
saved offers to database (table name OFFERS_APARTMENTS_SALE)
initiating download of description of offers
downloaded description of offers: 20 out of 778
downloaded description of offers: 40 out of 778
downloaded description of offers: 60 out of 778
downloaded description of offers: 80 out of 778
downloaded description of offers: 100 out of 778
downloaded description of offers: 120 out of 778
downloaded description of offers: 140 out of 778
downloaded description of offers: 160 out of 778
downloaded description of offers: 180 out of 778
downloaded description of offers: 200 out of 778
downloaded description of offers: 220 out of 778
downloaded description of offers: 240 out of 778
downloaded description of offers: 260 out of 778
downloaded description of offers: 280 out of 778
downloaded description of offers: 300 out of 778
downloaded description of offers: 320 out of 778
downloaded description of offers: 340 out of 778
downloaded description of offers: 360 out of 778
downloaded description of offers: 380 out of 778
downloaded description of offers: 400 out of 778
downloaded description of offers: 420 out of 778
downloaded description of offers: 440 out of 778
downloaded description of offers: 460 out of 778
downloaded description of offers: 480 out of 778
downloaded description of offers: 500 out of 778
downloaded description of offers: 520 out of 778
downloaded description of offers: 540 out of 778
downloaded description of offers: 560 out of 778
downloaded description of offers: 580 out of 778
downloaded description of offers: 600 out of 778
downloaded description of offers: 620 out of 778
downloaded description of offers: 640 out of 778
downloaded description of offers: 660 out of 778
downloaded description of offers: 680 out of 778
downloaded description of offers: 700 out of 778
downloaded description of offers: 720 out of 778
downloaded description of offers: 740 out of 778
downloaded description of offers: 760 out of 778
downloaded description of offers: 778 out of 778

decoding responses with description of offers:   0%|          | 0/778 [00:00<?, ?it/s]

Add these values to description_items_dict in sreality_api_dictionaries.py:
Series([], dtype: object)
saving description of offers to database (table DESCRIPTION_APARTMENTS_SALE)
saved description of offers to database (table DESCRIPTION_APARTMENTS_SALE)

**Load the data from SQLite:**

In [7]:
import sqlite3

In [8]:
path_to_sqlite='estate_data.sqlite'
con = sqlite3.connect(path_to_sqlite)

In [9]:
print("Tables in our database:\n")
cursor = con.cursor()
# Getting all tables from sqlite_master
sql_query = """SELECT name FROM sqlite_master WHERE type='table';"""
cursor.execute(sql_query)
sqlite_tables = cursor.fetchall()
sqlite_tables = [*map(lambda table: table[0] ,sqlite_tables)]
print(sqlite_tables)
del sqlite_tables
del sql_query

Tables in our database:

['OFFERS_APARTMENTS_SALE', 'DESCRIPTION_APARTMENTS_SALE']

In [10]:
import pandas as pd

In [11]:
df_description = pd.read_sql('SELECT * FROM DESCRIPTION_APARTMENTS_SALE', con = con)

In [12]:
df_offers = pd.read_sql('SELECT * FROM OFFERS_APARTMENTS_SALE', con = con)

In [13]:
df_offers.shape, df_description.shape

((778, 19), (778, 74))

**Note:** dataset's rows numbers may differ as some offers might have disappeared before description download was finished.

In [14]:
# Closing the connection
con.close()

Datasets view:

In [15]:
df_offers

,hash_id,price,price_czk,price_czk_unit,price_czk_name,area,lat,lon,locality,apartment_type,is_auction,exclusively_at_rk,category_main,category_sub,category_type,company_id,company_name,date_download,locality_region_id
0,1416877132,6339000,6339000,,Celková cena,33,50.683424,15.764948,"Pec pod Sněžkou - Velká Úpa, okres Trutnov",2+kk,0,1,1,4,1,31704.0,T.L.S group,2023-02-12,6
1,3462220,1313000,1313000,,Celková cena,24,50.627229,15.818803,"Svoboda nad Úpou, okres Trutnov",1+1,0,0,1,3,1,NaN,None,2023-02-12,6
2,2165167180,3355000,3355000,,Celková cena,68,50.292486,15.872371,"Smiřice, okres Hradec Králové",3+kk,0,0,1,6,1,NaN,None,2023-02-12,6
3,1315952460,8208000,8208000,,Celková cena,63,50.627664,15.717890,"Černý Důl, okres Trutnov",3+kk,0,0,1,6,1,NaN,None,2023-02-12,6
4,4092053852,5143000,5143000,,Celková cena,38,50.297350,16.357943,"Deštné v Orlických horách, okres Rychnov nad K...",1+kk,0,0,1,2,1,NaN,None,2023-02-12,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
773,593866332,5267000,5267000,,Celková cena,53,50.619672,15.616670,"Vrchlabí, okres Trutnov",3+1,0,1,1,7,1,2293.0,AC Real,2023-02-12,6
774,2310814556,0,0,,Celková cena,28,50.718855,15.616737,"Špindlerův Mlýn, okres Trutnov",1+kk,0,1,1,2,1,16159.0,Sotheby´s International Realty Czech Republic,2023-02-12,6
775,3721243484,472000,472000,,Celková cena,48,50.583536,16.408841,"Šonov, okres Náchod",3+1,0,0,1,7,1,NaN,None,2023-02-12,6
776,1996766812,5051000,5051000,,Celková cena,43,50.619672,15.616670,"Vrchlabí, okres Trutnov",2+1,0,1,1,5,1,2293.0,AC Real,2023-02-12,6
777,2921480540,9411000,9411000,,Celková cena,30,50.723619,15.616411,"Špindlerův Mlýn, okres Trutnov",2+kk,0,0,1,4,1,16753.0,Realityspindl.com,2023-02-12,6

In [16]:
df_description

,hash_id,description,discounted,price_original,id_order,date_update,building_type,building_condition,apartment_type,apartment_count,...,expert_opinion,ownership,privatization,loggia,housing_costs,attic_construction,terrace,cellar,date_development_completion,balcony
0,1416877132,Výstavba apartmánového resortu v Peci pod Sněž...,None,None,D32,02.02.2023,None,Ve výstavbě,Podkrovní,None,...,None,Osobní,None,None,None,NaN,None,None,None,None
1,3462220,Hledáte pro sebe zázemí na zimní sporty a nech...,None,None,825485,Dnes,None,Dobrý,None,None,...,None,Osobní,None,None,None,NaN,None,1,None,None
2,2165167180,"Dobrý den, nabízím Vám k prodeji vkusně zrekon...",4 599 000,4 849 000,PM230115,Dnes,None,Po rekonstrukci,None,None,...,None,Osobní,None,None,None,NaN,None,None,None,None
3,1315952460,"Obec Čistá, to je krásné místo k relaxaci v kl...",None,None,01192-1,Dnes,None,Ve výstavbě,None,None,...,None,Osobní,None,None,None,NaN,None,None,None,2
4,4092053852,Světlý apartmán ve 2NP dispozičně řešený jako ...,None,None,00954,Dnes,None,Novostavba,None,None,...,None,Osobní,None,None,None,NaN,23,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
773,593866332,Apartmán o velikosti 3+1 je skvělou volbou pro...,None,None,D050,06.04.2022,None,Novostavba,None,None,...,None,Osobní,None,4,None,NaN,None,None,None,None
774,2310814556,O PROJEKTU\r\n\r\nZe dveří rovnou na svah a op...,None,None,0559-11,27.01.2023,None,Projekt,None,None,...,None,Osobní,None,None,None,NaN,None,None,None,176
775,3721243484,Nabízíme vám exklusivně v rámci probíhajícího ...,None,None,IR1682021,02.01.2023,None,Dobrý,None,None,...,None,Družstevní,None,None,None,NaN,None,1,None,None
776,1996766812,Apartmán o velikosti 2+1 je skvělou investiční...,None,None,D053,06.04.2022,None,Novostavba,None,None,...,None,Osobní,None,6,None,NaN,None,None,None,None
777,2921480540,Realitní kancelář Reality Špindl Vám exkluzivn...,None,None,370,23.06.2022,None,Velmi dobrý,None,None,...,None,Osobní,None,None,None,NaN,None,3,None,None

# One can check 'EDA - Flats for sale.ipynb' to see an exemplary EDA.